// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX_TCMeAjPM5Zpb8yHJUoxfFp8au27_xk',
    appId: '1:560958239079:web:25460131e29cfda87a7fc2',
    messagingSenderId: '560958239079',
    projectId: 'fayas-car-rental-app01',
    authDomain: 'fayas-car-rental-app01.firebaseapp.com',
    storageBucket: 'fayas-car-rental-app01.firebasestorage.app',
    measurementId: 'G-E3X318V93Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6GEX12bbpBbO4bEKaZMp8DCuFwMcDFW8',
    appId: '1:560958239079:android:7dba8e89075d29617a7fc2',
    messagingSenderId: '560958239079',
    projectId: 'fayas-car-rental-app01',
    storageBucket: 'fayas-car-rental-app01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtXG70x9JlIx1s33Ua-BEt1rwI1C5EOQ0',
    appId: '1:560958239079:ios:9d1727f4f48988207a7fc2',
    messagingSenderId: '560958239079',
    projectId: 'fayas-car-rental-app01',
    storageBucket: 'fayas-car-rental-app01.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtXG70x9JlIx1s33Ua-BEt1rwI1C5EOQ0',
    appId: '1:560958239079:ios:9d1727f4f48988207a7fc2',
    messagingSenderId: '560958239079',
    projectId: 'fayas-car-rental-app01',
    storageBucket: 'fayas-car-rental-app01.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX_TCMeAjPM5Zpb8yHJUoxfFp8au27_xk',
    appId: '1:560958239079:web:48e75816e41229977a7fc2',
    messagingSenderId: '560958239079',
    projectId: 'fayas-car-rental-app01',
    authDomain: 'fayas-car-rental-app01.firebaseapp.com',
    storageBucket: 'fayas-car-rental-app01.firebasestorage.app',
    measurementId: 'G-VGKQT0QQ5F',
  );
}
